#ifndef CONSTANTS_H
#define CONSTANTS_H


// Umgebung
#define INITIAL_WINDOW_WIDTH 1200
#define INITIAL_WINDOW_HEIGHT 800

#define MAX_FPS 120
#define MIN_FRAME_DURATION (1000.0f / MAX_FPS)
#define MAX_FRAME_DURATION 100


// Grössen in Längeneinheiten (units)
#define PADDLE_HEIGHT 5
#define PADDLE_WIDTH 1
#define PADDLE_OFFSET 2
#define BALL_SIZE 1
#define BALL_VELOCITY_FACTOR 40 // Einheiten pro Sekunde
#define PADDLE_VELOCITY 40

// Mathe
#define PI 3.14159f
#define MAX_BOUNCE_OFF_ANGLE (PI / 4.0f) // 45°



#define INITIAL_PADDLE_WIDTH (INITIAL_WINDOW_WIDTH / 50)
#define INITIAL_PADDLE_HEIGHT (INITIAL_WINDOW_HEIGHT / 8)

#define INITIAL_PADDLE_OFFSET (INITIAL_WINDOW_WIDTH / 50)

#define INITIAL_BALL_SIZE (INITIAL_PADDLE_WIDTH)

#define INITIAL_BALL_VELOCITY (INITIAL_WINDOW_WIDTH / 5.0)

#define INITIAL_PADDLE_VELOCITY (INITIAL_BALL_VELOCITY)



#endif